CREATE TABLE [raw_data] (
[ID] INTEGER  PRIMARY KEY AUTOINCREMENT NOT NULL,
[Seen] TEXT  NULL,
[Data] TEXT  NULL
)

CREATE TABLE [relationships] (
[ID] INTEGER  NOT NULL PRIMARY KEY AUTOINCREMENT,
[Seen] TEXT  NULL,
[BadgeNum1] TEXT  NULL,
[BadgeNum2] TEXT  NULL,
UNIQUE(BadgeNum1,BadgeNum2)
)

CREATE TABLE [badges] (
[ID] INTEGER  PRIMARY KEY AUTOINCREMENT NOT NULL,
[Seen] TEXT  NULL,
[BadgeNumber] TEXT  UNIQUE NULL
)